name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build index.html
        run: pandoc README.md -o index.html

      - name: Deploy HTML files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: merah.cassia.ifost.org.au
          username: numbertarget
          key: ${{ secrets.NUMBER_TARGET_SSH_KEY }}
          source: "*.html"
          target: /var/www/vhosts/learning-theory.arithmetic.guru/htdocs/
