name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build index.html
        run: pandoc README.md -o index.html

      - name: Setup SSH
        env:
          SSH_KEY: ${{ env.NUMBER_TARGET_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan merah.cassia.ifost.org.au >> ~/.ssh/known_hosts

      - name: Debug SSH setup
        env:
          SSH_KEY: ${{ env.NUMBER_TARGET_SSH_KEY }}
        run: |
          head -n 1 ~/.ssh/id_ed25519

      - name: Debug SSH setup 2
        env:
          SSH_KEY: ${{ env.NUMBER_TARGET_SSH_KEY }}
        run: |
          echo "This is the key:\n$SSH_KEY\nThe end"

      - name: Deploy HTML files
        run: |
          scp -i ~/.ssh/id_ed25519 *.html merah.cassia.ifost.org.au:/var/www/vhosts/learning-theory.arithmetic.guru/htdocs/
