name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build index.html
        run: |
          # Create a modified README that skips the header content for prettier formatting
          sed -n '8,$p' README.md > README_body.md
          pandoc README_body.md -o index.html --template=index-template.html --css=index-style.css --metadata title="Learning Theory Games"

      - name: Deploy HTML files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: merah.cassia.ifost.org.au
          username: numbertarget
          key: ${{ secrets.NUMBER_TARGET_SSH_KEY }}
          source: "*.html,*.css"
          target: /var/www/vhosts/learning-theory.arithmetic.guru/htdocs/
